// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// admm_lasso
Rcpp::List admm_lasso(const arma::mat& A, const arma::colvec& b, arma::colvec& u, arma::colvec& z, const double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_lasso(SEXP ASEXP, SEXP bSEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_lasso(A, b, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_adalasso
Rcpp::List admm_adalasso(const arma::mat& A, const arma::colvec& b, arma::vec& var_weights, arma::colvec& u, arma::colvec& z, const double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_adalasso(SEXP ASEXP, SEXP bSEXP, SEXP var_weightsSEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_adalasso(A, b, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_glasso
Rcpp::List admm_glasso(const arma::mat& A, const arma::colvec& b, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, arma::colvec& u, arma::colvec& z, const double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_glasso(SEXP ASEXP, SEXP bSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_glasso(A, b, groups, group_weights, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_spglasso
Rcpp::List admm_spglasso(const arma::mat& A, const arma::colvec& b, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, arma::vec& var_weights_L1, arma::colvec& u, arma::colvec& z, const double lambda1, const double lambda2, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_spglasso(SEXP ASEXP, SEXP bSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP var_weights_L1SEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights_L1(var_weights_L1SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_spglasso(A, b, groups, group_weights, var_weights, var_weights_L1, u, z, lambda1, lambda2, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_ovglasso
Rcpp::List admm_ovglasso(const arma::mat& A, const arma::colvec& b, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, arma::colvec& u, arma::colvec& z, const double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_ovglasso(SEXP ASEXP, SEXP bSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_ovglasso(A, b, groups, group_weights, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_lasso_fast
Rcpp::List admm_lasso_fast(const arma::mat& A, arma::vec& b, arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_lasso_fast(SEXP ASEXP, SEXP bSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_lasso_fast(A, b, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_glasso_fast
Rcpp::List admm_glasso_fast(const arma::mat& A, arma::vec& b, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, const arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_glasso_fast(SEXP ASEXP, SEXP bSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_glasso_fast(A, b, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_spglasso_fast
Rcpp::List admm_spglasso_fast(const arma::mat& A, arma::vec& b, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, arma::vec& var_weights_L1, const arma::vec lambda, const double alpha, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_spglasso_fast(SEXP ASEXP, SEXP bSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP var_weights_L1SEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights_L1(var_weights_L1SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_spglasso_fast(A, b, groups, group_weights, var_weights, var_weights_L1, lambda, alpha, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_ovglasso_fast
Rcpp::List admm_ovglasso_fast(const arma::mat& A, arma::vec& b, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, const arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_ovglasso_fast(SEXP ASEXP, SEXP bSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_ovglasso_fast(A, b, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_adalasso_fast
Rcpp::List admm_adalasso_fast(const arma::mat& A, arma::vec& b, arma::vec& var_weights, const arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_adalasso_fast(SEXP ASEXP, SEXP bSEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_adalasso_fast(A, b, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_lasso_cov_fast
Rcpp::List admm_lasso_cov_fast(arma::mat& W, arma::mat Z, arma::vec& y, const arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_lasso_cov_fast(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_lasso_cov_fast(W, Z, y, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_glasso_cov_fast
Rcpp::List admm_glasso_cov_fast(arma::mat& W, arma::mat Z, arma::vec& y, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, const arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_glasso_cov_fast(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_glasso_cov_fast(W, Z, y, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_ovglasso_cov_fast
Rcpp::List admm_ovglasso_cov_fast(arma::mat& W, arma::mat& Z, arma::vec& y, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, const arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_ovglasso_cov_fast(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_ovglasso_cov_fast(W, Z, y, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_adalasso_cov_fast
Rcpp::List admm_adalasso_cov_fast(arma::mat& W, arma::mat& Z, arma::vec& y, arma::vec& var_weights, const arma::vec lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_adalasso_cov_fast(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_adalasso_cov_fast(W, Z, y, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_spglasso_cov_fast
Rcpp::List admm_spglasso_cov_fast(arma::mat& W, arma::mat& Z, arma::vec& y, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, arma::vec& var_weights_L1, const arma::vec lambda, const double alpha, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_spglasso_cov_fast(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP var_weights_L1SEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights_L1(var_weights_L1SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_spglasso_cov_fast(W, Z, y, groups, group_weights, var_weights, var_weights_L1, lambda, alpha, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_lasso_cov
Rcpp::List admm_lasso_cov(arma::mat& W, arma::mat& Z, const arma::colvec& y, arma::colvec& u, arma::colvec& z, const double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_lasso_cov(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_lasso_cov(W, Z, y, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_glasso_cov
Rcpp::List admm_glasso_cov(arma::mat& W, arma::mat& Z, arma::vec& y, arma::colvec& u, arma::colvec& z, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_glasso_cov(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP uSEXP, SEXP zSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_glasso_cov(W, Z, y, u, z, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_ovglasso_cov
Rcpp::List admm_ovglasso_cov(arma::mat& W, arma::mat& Z, arma::vec& y, arma::colvec& u, arma::colvec& z, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_ovglasso_cov(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP uSEXP, SEXP zSEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_ovglasso_cov(W, Z, y, u, z, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_adalasso_cov
Rcpp::List admm_adalasso_cov(arma::mat W, arma::mat& Z, arma::colvec& y, arma::vec& var_weights, arma::colvec& u, arma::colvec& z, const double lambda, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_adalasso_cov(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP var_weightsSEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambdaSEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_adalasso_cov(W, Z, y, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}
// admm_spglasso_cov
Rcpp::List admm_spglasso_cov(arma::mat& W, arma::mat& Z, arma::vec& y, arma::mat& groups, arma::vec& group_weights, arma::vec& var_weights, arma::vec& var_weights_L1, arma::colvec& u, arma::colvec& z, const double lambda1, const double lambda2, bool rho_adaptation, double rho, const double tau, const double mu, const double reltol, const double abstol, const int maxiter, const int ping);
RcppExport SEXP _fdaSP_admm_spglasso_cov(SEXP WSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP groupsSEXP, SEXP group_weightsSEXP, SEXP var_weightsSEXP, SEXP var_weights_L1SEXP, SEXP uSEXP, SEXP zSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP rho_adaptationSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP muSEXP, SEXP reltolSEXP, SEXP abstolSEXP, SEXP maxiterSEXP, SEXP pingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group_weights(group_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights(var_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type var_weights_L1(var_weights_L1SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< bool >::type rho_adaptation(rho_adaptationSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< const double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int >::type ping(pingSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_spglasso_cov(W, Z, y, groups, group_weights, var_weights, var_weights_L1, u, z, lambda1, lambda2, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fdaSP_admm_lasso", (DL_FUNC) &_fdaSP_admm_lasso, 13},
    {"_fdaSP_admm_adalasso", (DL_FUNC) &_fdaSP_admm_adalasso, 14},
    {"_fdaSP_admm_glasso", (DL_FUNC) &_fdaSP_admm_glasso, 16},
    {"_fdaSP_admm_spglasso", (DL_FUNC) &_fdaSP_admm_spglasso, 18},
    {"_fdaSP_admm_ovglasso", (DL_FUNC) &_fdaSP_admm_ovglasso, 16},
    {"_fdaSP_admm_lasso_fast", (DL_FUNC) &_fdaSP_admm_lasso_fast, 11},
    {"_fdaSP_admm_glasso_fast", (DL_FUNC) &_fdaSP_admm_glasso_fast, 14},
    {"_fdaSP_admm_spglasso_fast", (DL_FUNC) &_fdaSP_admm_spglasso_fast, 16},
    {"_fdaSP_admm_ovglasso_fast", (DL_FUNC) &_fdaSP_admm_ovglasso_fast, 14},
    {"_fdaSP_admm_adalasso_fast", (DL_FUNC) &_fdaSP_admm_adalasso_fast, 12},
    {"_fdaSP_admm_lasso_cov_fast", (DL_FUNC) &_fdaSP_admm_lasso_cov_fast, 12},
    {"_fdaSP_admm_glasso_cov_fast", (DL_FUNC) &_fdaSP_admm_glasso_cov_fast, 15},
    {"_fdaSP_admm_ovglasso_cov_fast", (DL_FUNC) &_fdaSP_admm_ovglasso_cov_fast, 15},
    {"_fdaSP_admm_adalasso_cov_fast", (DL_FUNC) &_fdaSP_admm_adalasso_cov_fast, 13},
    {"_fdaSP_admm_spglasso_cov_fast", (DL_FUNC) &_fdaSP_admm_spglasso_cov_fast, 17},
    {"_fdaSP_admm_lasso_cov", (DL_FUNC) &_fdaSP_admm_lasso_cov, 14},
    {"_fdaSP_admm_glasso_cov", (DL_FUNC) &_fdaSP_admm_glasso_cov, 17},
    {"_fdaSP_admm_ovglasso_cov", (DL_FUNC) &_fdaSP_admm_ovglasso_cov, 17},
    {"_fdaSP_admm_adalasso_cov", (DL_FUNC) &_fdaSP_admm_adalasso_cov, 15},
    {"_fdaSP_admm_spglasso_cov", (DL_FUNC) &_fdaSP_admm_spglasso_cov, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdaSP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
