# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name  fdaSP.internal
#' @keywords internal
.admm_lasso <- function(A, b, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_lasso`, A, b, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_adalasso <- function(A, b, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_adalasso`, A, b, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_glasso <- function(A, b, groups, group_weights, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_glasso`, A, b, groups, group_weights, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_spglasso <- function(A, b, groups, group_weights, var_weights, var_weights_L1, u, z, lambda1, lambda2, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_spglasso`, A, b, groups, group_weights, var_weights, var_weights_L1, u, z, lambda1, lambda2, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_ovglasso <- function(A, b, groups, group_weights, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_ovglasso`, A, b, groups, group_weights, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_lasso_fast <- function(A, b, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_lasso_fast`, A, b, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_glasso_fast <- function(A, b, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_glasso_fast`, A, b, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_spglasso_fast <- function(A, b, groups, group_weights, var_weights, var_weights_L1, lambda, alpha, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_spglasso_fast`, A, b, groups, group_weights, var_weights, var_weights_L1, lambda, alpha, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_ovglasso_fast <- function(A, b, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_ovglasso_fast`, A, b, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_adalasso_fast <- function(A, b, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_adalasso_fast`, A, b, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_lasso_cov_fast <- function(W, Z, y, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_lasso_cov_fast`, W, Z, y, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_glasso_cov_fast <- function(W, Z, y, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_glasso_cov_fast`, W, Z, y, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_ovglasso_cov_fast <- function(W, Z, y, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_ovglasso_cov_fast`, W, Z, y, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_adalasso_cov_fast <- function(W, Z, y, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_adalasso_cov_fast`, W, Z, y, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_spglasso_cov_fast <- function(W, Z, y, groups, group_weights, var_weights, var_weights_L1, lambda, alpha, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_spglasso_cov_fast`, W, Z, y, groups, group_weights, var_weights, var_weights_L1, lambda, alpha, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_lasso_cov <- function(W, Z, y, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_lasso_cov`, W, Z, y, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_glasso_cov <- function(W, Z, y, u, z, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_glasso_cov`, W, Z, y, u, z, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_ovglasso_cov <- function(W, Z, y, u, z, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_ovglasso_cov`, W, Z, y, u, z, groups, group_weights, var_weights, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_adalasso_cov <- function(W, Z, y, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_adalasso_cov`, W, Z, y, var_weights, u, z, lambda, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @name  fdaSP.internal
#' @keywords internal
.admm_spglasso_cov <- function(W, Z, y, groups, group_weights, var_weights, var_weights_L1, u, z, lambda1, lambda2, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping) {
    .Call(`_fdaSP_admm_spglasso_cov`, W, Z, y, groups, group_weights, var_weights, var_weights_L1, u, z, lambda1, lambda2, rho_adaptation, rho, tau, mu, reltol, abstol, maxiter, ping)
}

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
NULL

